version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ocode-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ocode:
    build: .
    container_name: ocode-assistant
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./:/workspace
      - ocode_cache:/home/ocode/.ocode
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OCODE_MODEL=llama3:8b
      - OCODE_VERBOSE=false
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: ["--help"]

  ocode-mcp:
    build: .
    container_name: ocode-mcp-server
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./:/workspace
    environment:
      - OLLAMA_HOST=http://ollama:11434
    working_dir: /workspace
    ports:
      - "8000:8000"
    command: ["python", "-m", "ocode_python.mcp.server", "--project-root", "/workspace"]

volumes:
  ollama_data:
    driver: local
  ocode_cache:
    driver: local