name: Test PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-test:
    name: Quick Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort mypy
    
    - name: Quick format check
      run: |
        black --check --diff ocode_python || echo "::warning::Black formatting issues found"
        isort --check-only --diff ocode_python || echo "::warning::isort import order issues found"
    
    - name: Quick lint
      run: |
        flake8 ocode_python --count --statistics || echo "::warning::Flake8 issues found"